### ISSUE TITLE
Cannot clone "CEP_Chipyard_ASIC" submodule

### ISSUE THREAD

**Issue by WRansohoff** [CommonEvaluationPlatform/CEP#17]
Hi there,

I am having trouble cloning the "CEP_Chipyard_ASIC" submodule in this repository.

It appears to refer to an llcad-github address, and I found HTTPS links to repositories listed under that Git instance in the [mit-ll/nemo](https://github.com/mit-ll/nemo) repository, but it appears that the "https://llcad-github.llan.ll.mit.edu/" address is no longer valid, or possibly no longer public. Have the "llcad-github" repositories been moved to a different address recently?

Thank you, and I apologize if this question is addressed in the documentation somewhere.

**Comment by bchetwynd** [comment]
There is a note in the README.md that ASIC-based CEP builds will fail due to missing files.  These files are in the non-releasable CEP_Chipyard_ASIC submodule which is not accessible as part of the open source release due to licensing issues.

**Comment by WRansohoff** [comment]
Ah, that makes sense. Sorry that I missed the note in the readme.
