### ISSUE TITLE
RTL-only build(s)?

### ISSUE THREAD

**Issue by lmg260a** [CommonEvaluationPlatform/CEP#25]
Hi, for various reasons I'm not able to use conda.
What I'm interested in is just a couple of RTL-only example designs.
is there a way to generate one or more w/o needing any tools?
Or if a tool is needed, what's the minimum?

**Comment by bchetwynd** [comment]
Unfortunately, Chipyard (on which the CEP is based) leverages conda, which installs a variety of package dependencies needed for RTL generation (running the Chisel generators). In theory, you could install all the dependencies manually (ubuntu and some python packages)... see conda-reqs/chipyard.yaml.  However, depending on what you are doing, you'll also need to install the riscv-tools for software crosscompilation.
