### ISSUE TITLE
BareMetal Test in CEP v4.7 hangs

### ISSUE THREAD

**Issue by jordankrim** [CommonEvaluationPlatform/CEP#40]
The bareMetal Test called macro4Mix exercises the RSA module.   I have attempted to replace this module with my own.  In CEP v4.4 and v4.5 this works and the simulation with Verilator passes, but in CEP v4.7 I replace it with mine and in the Verilator simulation it hangs,   In CEP v4.4 and 4.5 the change to incorporate my own is modifying the resources in the rsa..scala.  In CEP 4.7 this has been moved to a file call cepPackage.scala.  I replace the resources in 2 places in this file (vs. 1 in the old CEP 4.4 and 4.5 rsa.scala file).  Is there some other "fix" I am missing to allow the macro4Mix to run and pass in CEP 4.7 as it did in CEP 4.4 and 4.5 instead fo hanging?

**Comment by jordankrim** [comment]
Found the issue.  The "mock_tss" file was in both places and it only belonged in 1.  After recompiling the Chipyard and the verilated code and rerunning with Verilator, it now passes.

**Comment by bchetwynd** [comment]
Thank you for sharing the note.
